package org.openehr.rm.ehr_extract.sync_extract;

/**
 * Generic model of a Request for an Extract, containing an Extract specification.
 */
public interface ExtractRequest extends Locatable {
  /**
   * Specification details of the request.
   */
  ExtractSpec getExtractSpec();

  /**
   * Update details of the request.
   */
  ExtractUpdateSpec getUpdateSpec();

  /**
   * Identifier of this Request, generated by requestor.
   */
  HierObjectId getUid();
}
